name = 'Canit Role Play'
port = 7788
players = 128
# password = 'ultra-password'
announce = false
# token = 'YOUR_TOKEN'
gamemode = 'Roleplay'
website = 'https://discord.gg/Bd7EBZuCEj'
language = 'ru'
description = 'RolePlay project GTA5 on alt:V Multiplayer'
modules = ['csharp-module', 'js-module', 'js-bytecode-module']
resources = ['chat', 'serverside', 'clientside']
debug = true